#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include <kernel/panic.h>

// defined in the boot assembly
extern uintptr_t __stack_chk_guard;

/**
 * Calls to this function are generated by the compiler
 * when the stack is smashed. (-fstack-protector needs to be enabled)
 */
extern "C"
[[ noreturn ]]
void __stack_chk_fail(void)
{
    panic("stack smashed!\n");
}