#include <stdint.h>
#include <stdlib.h>

#include <compiler/macros.h>
#include <kernel/panic.h>

#if IS_32_BIT
    #define STACK_CHK_GUARD 0x1234abcd
#elif IS_64_BIT
    #define STACK_CHK_GUARD 0x0123456789abcdef
#else
    #error "expected 32-bit or 64-bit environnment"
#endif

// canary value used to check for stack-smashing
extern constexpr uintptr_t __stack_chk_guard = STACK_CHK_GUARD;

/**
 * Calls to this function are generated by the compiler
 * when the stack is smashed. (-fstack-protector needs to be enabled)
 */
extern "C"
[[ noreturn ]]
void __stack_chk_fail(void)
{
    panic("stack smashed!\n");
}