#include <stdint.h>
#include <stdlib.h>

#include <kernel/kernel.h>

// canary value used to check for stack-smashing
extern constexpr uintptr_t __stack_chk_guard = 0x0123456789abcdef;

/**
 * Calls to this function are generated by the compiler
 * when the stack is smashed. (-fstack-protector needs to be enabled)
 */
extern "C"
[[ noreturn ]]
void __stack_chk_fail(void)
{
    kernel_panic("stack smashed!\n");
}