#include <stdint.h>
#include <stdlib.h>

#include <kernel/kernel.h>

#ifdef TEST_BUILD
#include <stdio.h>
#endif

// canary value used to check for stack-smashing
extern constexpr uintptr_t __stack_chk_guard = 0x0123456789abcdef;

/**
 * Calls to this function are generated by the compiler
 * when the stack is smashed. (-fstack-protector needs to be enabled)
 */
#ifndef TEST_BUILD
extern "C"
[[ noreturn ]]
void __stack_chk_fail(void)
{
    kernel_panic("stack smashed!\n");
}
#else
extern "C"
void __stack_chk_fail(void)
{
    printf("stack smash test: PASSED\n");
}
#endif